name: Build for iOS

on:
  push:
    tags: 
      - v*

jobs: 
  build: 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: ncipollo/release-action@v1
        with:
          # /Users/runner/work/hikagefinder-app/hikagefinder-app/build/ios/iphoneos/Runner.app
          artifacts: "/Users/runner/work/hikagefinder-app/hikagefinder-app/build/ios/iphoneos/*.app"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
